Wip capo
giantswarm/capi-image-builder pull request #2
Opened 2022-06-27 18:53 UTC by ericgraf

Initial code towards capo pipeline

2022-06-30 05:22 UTC, AverageMarcus requested changes

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/pipelines/openstack/detect/detect-k8s-versions.yaml
> +            cat -e $(results.releases.path)
```suggestion
          image: quay.io/giantswarm/docker-kubectl:latest
          script: |-
            curl "https://api.github.com/repos/kubernetes/kubernetes/releases?per_page=100" | \
            	jq '.[] | select(.tag_name | test("^v1\\.[0-9]+\\.[0-9]+$")) | .tag_name' | \
            	tee  $(results.releases.path)
```

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/pipelines/openstack/detect/detect-k8s-versions.yaml
> +    - name: get-k8s-releases
This should be pulled out to a reusable task

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/secrets/openstack/secret-s3-endpoint.yaml
> +  name: aws-credentials
Might be worth making this more specifically named as likely going to differ from credentials used when building CAPA images.

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/tasks/openstack/aws-cli.yaml
> +{{ if eq .Values.provider.kind "openstack" }}
Any reason for this being openstack specific?

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/tasks/openstack/build-capi-image.yaml
> +  name: build-capo-image
Any reason this needs to be capo specific?

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/triggers/openstack/detect/cronjob-cleanup-triggers.yaml
> +{{ if eq .Values.provider.kind "openstack" }}
This isn't CAPO specific, it'll delete pipelineruns from all CAPI builds. It would also only keep the last 3 of all CAPI builds.

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/templates/triggers/openstack/detect/cronjob-trigger-k8s-version-detection.yaml
> +  schedule: "*/10 * * * *"
Do we really need to be checking for new releases that often?

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/values.yaml
> +  excludeVersions:
I'm still not sure about the logic of this. Would it not be better to just target all new versions released?

2022-06-30 05:22 UTC, AverageMarcus commented on helm/capi-image-builder/values.yaml
> +tektonCleaner:
I'm not sure it makes sense to have this as part of this app. I'd prefer a more generic cleaner that can be deployed as it's own app, and used for other pipelines if needed.

2022-06-30 13:11 UTC, AverageMarcus commented on helm/capi-image-builder/templates/pipelines/build/build-capi-image.yaml
> +        {{ if eq .Values.provider.kind "openstack" }}
This is still assuming different deployments per provider.

2022-06-30 13:15 UTC, ericgraf commented on helm/capi-image-builder/templates/pipelines/openstack/build/build-capo-image.yaml
> +  name: k8s-build
Changed the name

2022-06-30 13:15 UTC, ericgraf commented on helm/capi-image-builder/templates/pipelines/openstack/detect/detect-k8s-versions.yaml
> +    - name: get-k8s-releases
done

2022-06-30 13:16 UTC, ericgraf commented on helm/capi-image-builder/templates/secrets/openstack/secret-s3-endpoint.yaml
> +  name: aws-credentials
Changed to support different output types. This secret only gets created is output s3 is enabled.

2022-06-30 13:17 UTC, ericgraf commented on helm/capi-image-builder/templates/tasks/openstack/build-capi-image.yaml
> +  name: build-capo-image
fixed. It is now generic.

2022-06-30 13:17 UTC, ericgraf commented on helm/capi-image-builder/templates/triggers/openstack/detect/cronjob-cleanup-triggers.yaml
> +{{ if eq .Values.provider.kind "openstack" }}
fixed

2022-06-30 13:17 UTC, ericgraf commented on helm/capi-image-builder/templates/triggers/openstack/detect/cronjob-trigger-k8s-version-detection.yaml
> +  schedule: "*/10 * * * *"
moved to once an hour

2022-06-30 13:21 UTC, ericgraf commented on helm/capi-image-builder/values.yaml
> +  excludeVersions:
I admit this one can be improved. 
There is a chance that the output locations may need specific releases and not only the latest one available. Lets say a new release has a known bug and we can only use a later release that isn't uploaded yet. This could help support that. 

As this repo evolves and our requirements,  I fully expect this to change.

2022-06-30 13:23 UTC, ericgraf commented on helm/capi-image-builder/values.yaml
> +tektonCleaner:
I changed the name and description of the value. Tekton is interesting where each environment might be setup differently. I'd still like the app the have the option to properly cleanup after itself in case this app is used in a general environment.

2022-07-04 14:00 UTC, ericgraf commented on helm/capi-image-builder/templates/pipelines/build/build-capi-image.yaml
> +        {{ if eq .Values.provider.kind "openstack" }}
Moved the make target to the values.yaml file and changed the output file name to be agnostic.

2022-07-05 07:52 UTC, pipo02mix commented on helm/capi-image-builder/templates/pipelines/build/build-capi-image.yaml
> -        - ubuntu-2004-kube-v$(params.k8sVersion)
If you remove it from here, where do you tell it the image version to build?

2022-07-05 11:06 UTC, ericgraf commented on helm/capi-image-builder/templates/pipelines/build/build-capi-image.yaml
> -        - ubuntu-2004-kube-v$(params.k8sVersion)
This is the s3 upload task which does the upload .  The task named build-capi-image on line 14 does the actual building of the image.

2022-07-05 11:16 UTC, fiunchinho commented on helm/capi-image-builder/templates/pipelines/detect/detect-k8s-versions.yaml
> +        value: "$(tasks.get-s3-existing-image.results.existingS3)"
This makes the `get-s3-existing-image` task mandatory, doesn't it? I think we have to always execute it, instead of checking `{{ if .Values.output.s3.enabled }}`

2022-07-05 11:17 UTC, fiunchinho commented on helm/capi-image-builder/templates/secrets/secret-s3-endpoint.yaml
> +{{ if .Values.output.s3.enabled }}
This credentials seem to be used for more than output, I'm not sure we can make them optional.

2022-07-05 11:19 UTC, fiunchinho commented on helm/capi-image-builder/templates/tasks/aws-cli.yaml
> +  name: aws-cli
Why define a task for the `aws-cli` instead of running steps with the `aws-cli` container image?

2022-07-05 11:53 UTC, fiunchinho commented
What are the benefits of making the detection part a tekton pipeline?

I think we can have a cronjob that runs a component to detect k8s versions to be built, but this component could be on its own repository, rather than inlined in a tekton task/pipeline. This component would then trigger the pipeline to build the image.

2022-07-05 12:23 UTC, ericgraf commented on helm/capi-image-builder/templates/pipelines/detect/detect-k8s-versions.yaml
> +        value: "$(tasks.get-s3-existing-image.results.existingS3)"
Thanks for pointing this out. I missed this one. 
I added additional checks based on the output enabled.

2022-07-05 13:06 UTC, AverageMarcus commented on helm/capi-image-builder/templates/pipelines/build/build-capi-image.yaml
> +  {{ if .Values.output.s3.enabled }}
If we're relying on Helm values like this to distinguish between providers (CAPO vs CAPG) then we might as well not use the same codebase.
I thought the idea was to have this deployed to a single instance of Tekton where we can then build all CAPI images from. If that's the case, this value will have to be true for it to support CAPO but then it will incorrectly be used for CAPG etc. when it shouldn't.

We need to have individual tasks that are generic enough to be based on their input params and then have a different Pipeline for the variations of providers.

2022-07-05 13:26 UTC, ericgraf commented on helm/capi-image-builder/templates/tasks/aws-cli.yaml
> +  name: aws-cli
I removed the task as sugested

2022-07-05 13:33 UTC, ericgraf commented on helm/capi-image-builder/templates/pipelines/build/build-capi-image.yaml
> +  {{ if .Values.output.s3.enabled }}
CAPO will likely support two options s3 upload and OpenStack Glance upload.  Knowing what images need to be build also needs to know about the output endpoints. 

Since this gets complicated fast and is based on the provider/customer we would need to deploy this app multiple times IMO. 

I'm hoping to make this as general as possible. @AverageMarcus  please let me know how we can accomplish this.

2022-08-09 09:10 UTC, closed without merging